dist: bionic
language: C++

before_install:
  - sudo apt-get -y install libboost-all-dev

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=OFF ..
  - cmake --build .
  - ctest --output-on-failure
  - cd ..
  - mkdir build_with_boost
  - cd build_with_boost
  - cmake -DSIFTER_USE_BOOST_VARIANT=ON -DBUILD_EXAMPLES=OFF ..
  - cmake --build .
  - ctest --output-on-failure