dist: bionic
language: C++

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=x86
  - TARGET_CPU=amd64

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=OFF ..
  - cmake --build .
  - ctest --output-on-failure